name: Vercel - chonk9k-telegram-miniapp: boombot

on:
  push:
    branches:
      - main

jobs:
  notify-vercel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Notify Vercel
        uses: vercel/repository-dispatch/actions/status@v1
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          state: success
          environment: production
